// <auto-generated />
namespace Debugtime.Common.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dblevel4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dblevel4));
        
        string IMigrationMetadata.Id
        {
            get { return "201709041901540_dblevel4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
